server:
  port: 8085

# -- Default spring configuration
spring:
  application:
    name: seller

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: <cleint-id>
            client-secret: <client secret>
            redirect-uri: https://bidd.kro.kr/login/oauth2/code/bidd
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: client_secret_post
            scope: account_email, profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    generate-ddl: true
  #    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.16.220.92:3306/ddib?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: <ec2서버 username>
    password: <ec2서버 password>

  data:
    redis:
      host: bidd.kro.kr
      port: 6379

  jwt:
    secret: <JWT secret key>

access:
  token:
    expiration:
      time: 864000000

refresh:
  token:
    expiration:
      time: 864000000

releaseHostName: bidd.kro.kr

#eureka:
#  instance:
#    hostname: bidd.kro.kr
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://k10c102.p.ssafy.io:8761/eureka/
